### ISSUE TITLE
Error: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by inhahe** [b5i/apple-playlist-downloader-cli#3]
inhahe@Inhahe-desktop:/mnt/c/Users/inhah$ apd "https://music.apple.com/us/playlist/90s-club-essentials/pl.310497207ff84c569a0a8c5a96fe2ba5"
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:process'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by b5i** [comment]
Maybe you should update your version of node
